name       : virt-viewer
version    : '6.0'
release    : 4
source     :
    - https://releases.pagure.org/virt-viewer/virt-viewer-6.0.tar.gz : 9037bd7773da4dae761871ec1ab646cfefb4d7e48b1504dddf315a548ccb18b2
license    : GPL-2.0
component  : network.client
summary    : Virt Viewer provides a graphical viewer for the guest OS display
description: |
    Virt Viewer provides a graphical viewer for the guest OS display
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - intltool
setup      : |
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
